#!/usr/bin/env bash
# =============================================================================
#  SCRIPT : 01_beginner_system_report.sh
#  LEVEL  : Beginner
#  PURPOSE: Generate a simple system report and save it to a file
#  USAGE  : bash 01_beginner_system_report.sh
#
#  CONCEPTS COVERED:
#    - Variables
#    - echo & printf
#    - Command substitution  $( )
#    - if / else conditions
#    - Redirecting output  > and >>
#    - Reading user input  read
#    - Basic string operations
# =============================================================================

# ── Step 1: Define Variables ──────────────────────────────────────────────────
# Variables store data. No spaces around the = sign.

REPORT_FILE="system_report_$(date '+%Y-%m-%d').txt"   # filename with today's date
DIVIDER="=============================================="

# ── Step 2: Colours for terminal output ──────────────────────────────────────
# ANSI escape codes make output colourful.
# \033[0m resets colour back to default.

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
CYAN="\033[0;36m"
RED="\033[0;31m"
RESET="\033[0m"

# ── Step 3: A reusable function ───────────────────────────────────────────────
# Functions let you group code and call it multiple times.
# Syntax:  function_name() { ... }

print_section() {
    # $1 is the first argument passed to this function
    local TITLE="$1"
    echo -e "\n${CYAN}>>> ${TITLE}${RESET}"     # coloured terminal output
    # Write plain text (no ANSI codes) to the report file
    printf "\n>>> %s\n" "$TITLE"  >> "$REPORT_FILE"
    echo "$DIVIDER" >> "$REPORT_FILE"
}

# ── Step 4: Welcome message & ask user name ───────────────────────────────────

clear
echo -e "${GREEN}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║     🖥  Beginner System Report Script    ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${RESET}"

# 'read' pauses and waits for the user to type something
echo -e "${YELLOW}What is your name?${RESET}"
read -r USER_NAME           # -r prevents backslash from being interpreted

# If user pressed Enter without typing, use a default
if [[ -z "$USER_NAME" ]]; then     # -z checks if variable is empty
    USER_NAME="Developer"
fi

echo -e "\nHello, ${GREEN}${USER_NAME}${RESET}! Generating your system report...\n"

# ── Step 5: Start writing the report file ─────────────────────────────────────
# '>' creates/overwrites a file.   '>>' appends to a file.

echo "$DIVIDER"                                > "$REPORT_FILE"
echo "  SYSTEM REPORT — Generated by: $USER_NAME"  >> "$REPORT_FILE"
echo "  Date : $(date '+%A, %d %B %Y')"        >> "$REPORT_FILE"
echo "  Time : $(date '+%H:%M:%S')"            >> "$REPORT_FILE"
echo "$DIVIDER"                                >> "$REPORT_FILE"

# ── Step 6: Gather system info using command substitution ─────────────────────
# $( command ) runs a command and captures its output as a string

print_section "BASIC SYSTEM INFORMATION"

HOSTNAME=$(hostname)                    # machine name
CURRENT_USER=$(whoami)                  # logged-in username
OS_NAME=$(uname -s)                     # Operating System name
KERNEL=$(uname -r)                      # Kernel version
ARCH=$(uname -m)                        # CPU architecture (x86_64, arm64 etc.)
SHELL_USED=$SHELL                       # current shell path

# printf formats output neatly with alignment
printf "  %-18s : %s\n" "Hostname"       "$HOSTNAME"         | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Logged-in User" "$CURRENT_USER"     | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "OS"             "$OS_NAME"          | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Kernel"         "$KERNEL"           | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Architecture"   "$ARCH"             | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Shell"          "$SHELL_USED"       | tee -a "$REPORT_FILE"

# ── Step 7: Uptime ────────────────────────────────────────────────────────────

print_section "UPTIME"
UPTIME_INFO=$(uptime -p 2>/dev/null || uptime)   # 2>/dev/null hides errors
echo "  $UPTIME_INFO" | tee -a "$REPORT_FILE"

# ── Step 8: Memory Usage ──────────────────────────────────────────────────────

print_section "MEMORY USAGE"

# Check if 'free' command exists on this system
if command -v free &>/dev/null; then
    free -h | tee -a "$REPORT_FILE"
else
    echo "  'free' command not available on this system." | tee -a "$REPORT_FILE"
fi

# ── Step 9: Disk Usage ────────────────────────────────────────────────────────

print_section "DISK USAGE"
df -h | tee -a "$REPORT_FILE"

# ── Step 10: Check disk if usage exceeds 80% ─────────────────────────────────
# This is a practical if/else example

DISK_USAGE_PERCENT=$(df / | awk 'NR==2 {print $5}' | tr -d '%')

echo "" | tee -a "$REPORT_FILE"

    # Write to terminal with colour; write plain text (no ANSI codes) to the file
    if [[ "$DISK_USAGE_PERCENT" -ge 80 ]]; then
        echo -e "  ${RED}⚠  WARNING: Root disk is ${DISK_USAGE_PERCENT}% full! Consider cleanup.${RESET}"
        echo "  WARNING: Root disk is ${DISK_USAGE_PERCENT}% full! Consider cleanup." >> "$REPORT_FILE"
    elif [[ "$DISK_USAGE_PERCENT" -ge 60 ]]; then
        echo -e "  ${YELLOW}⚡  NOTICE: Root disk is ${DISK_USAGE_PERCENT}% full.${RESET}"
        echo "  NOTICE: Root disk is ${DISK_USAGE_PERCENT}% full." >> "$REPORT_FILE"
    else
        echo -e "  ${GREEN}✅  Disk health is good. Usage: ${DISK_USAGE_PERCENT}%${RESET}"
        echo "  Disk health is good. Usage: ${DISK_USAGE_PERCENT}%" >> "$REPORT_FILE"
    fi

# ── Step 11: List last 5 logged-in users ─────────────────────────────────────

print_section "LAST 5 LOGINS"
last -n 5 2>/dev/null | tee -a "$REPORT_FILE" || echo "  (last command not available)" | tee -a "$REPORT_FILE"

# ── Step 12: Final summary ────────────────────────────────────────────────────

echo "" | tee -a "$REPORT_FILE"
echo "$DIVIDER" | tee -a "$REPORT_FILE"
echo "  END OF REPORT" | tee -a "$REPORT_FILE"
echo "$DIVIDER" | tee -a "$REPORT_FILE"

echo ""
echo -e "${GREEN}✅  Report saved to: ${YELLOW}${REPORT_FILE}${RESET}"
echo -e "${CYAN}    Tip: Open it with:  cat ${REPORT_FILE}${RESET}"
echo ""
