#!/usr/bin/env bash
# =============================================================================
# Script: 01_beginner_system_report.sh
# Problem Statement: Generate a foundational system report covering OS, kernel, CPU, memory, and disk health metrics, outputting to both terminal and file.
# =============================================================================

REPORT_FILE="system_report_$(date '+%Y-%m-%d').txt"
DIVIDER="=============================================="

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
CYAN="\033[0;36m"
RED="\033[0;31m"
RESET="\033[0m"

print_section() {
    local TITLE="$1"
    echo -e "\n${CYAN}>>> ${TITLE}${RESET}"
    printf "\n>>> %s\n" "$TITLE"  >> "$REPORT_FILE"
    echo "$DIVIDER" >> "$REPORT_FILE"
}

check_disk_health_indicator() {
    local USAGE_PERCENT
    USAGE_PERCENT=$(df / | awk 'NR==2 {gsub("%",""); print $5}')
    if (( USAGE_PERCENT >= 85 )); then
        echo -e "${RED}⚠ Root filesystem capacity alert: ${USAGE_PERCENT}% utilized!${RESET}"
    else
        echo -e "${GREEN}✔ Root filesystem healthy: ${USAGE_PERCENT}% utilized.${RESET}"
    fi
}

clear
echo -e "${GREEN}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║     🖥  Beginner System Report Script    ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${RESET}"

echo -e "${YELLOW}What is your name?${RESET}"
read -r USER_NAME

if [[ -z "$USER_NAME" ]]; then
    USER_NAME="Developer"
fi

echo -e "\nHello, ${GREEN}${USER_NAME}${RESET}! Generating your system report...\n"

echo "$DIVIDER"                                > "$REPORT_FILE"
echo "  SYSTEM REPORT — Generated by: $USER_NAME"  >> "$REPORT_FILE"
echo "  Date : $(date '+%A, %d %B %Y')"        >> "$REPORT_FILE"
echo "  Time : $(date '+%H:%M:%S')"            >> "$REPORT_FILE"
echo "$DIVIDER"                                >> "$REPORT_FILE"

print_section "BASIC SYSTEM INFORMATION"

HOSTNAME=$(hostname)
CURRENT_USER=$(whoami)
OS_NAME=$(uname -s)
KERNEL=$(uname -r)
ARCH=$(uname -m)
SHELL_USED=$SHELL

printf "  %-18s : %s\n" "Hostname"       "$HOSTNAME"         | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Logged-in User" "$CURRENT_USER"     | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "OS"             "$OS_NAME"          | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Kernel"         "$KERNEL"           | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Architecture"   "$ARCH"             | tee -a "$REPORT_FILE"
printf "  %-18s : %s\n" "Shell"          "$SHELL_USED"       | tee -a "$REPORT_FILE"

print_section "UPTIME"
UPTIME_INFO=$(uptime -p 2>/dev/null || uptime)
echo "  $UPTIME_INFO" | tee -a "$REPORT_FILE"

print_section "MEMORY USAGE"

if command -v free &>/dev/null; then
    free -h | tee -a "$REPORT_FILE"
else
    echo "  'free' command not available on this system." | tee -a "$REPORT_FILE"
fi

print_section "DISK USAGE"
df -h | tee -a "$REPORT_FILE"

DISK_USAGE_PERCENT=$(df / | awk 'NR==2 {print $5}' | tr -d '%')

echo "" | tee -a "$REPORT_FILE"

    if [[ "$DISK_USAGE_PERCENT" -ge 80 ]]; then
        echo -e "  ${RED}⚠  WARNING: Root disk is ${DISK_USAGE_PERCENT}% full! Consider cleanup.${RESET}"
        echo "  WARNING: Root disk is ${DISK_USAGE_PERCENT}% full! Consider cleanup." >> "$REPORT_FILE"
    elif [[ "$DISK_USAGE_PERCENT" -ge 60 ]]; then
        echo -e "  ${YELLOW}⚡  NOTICE: Root disk is ${DISK_USAGE_PERCENT}% full.${RESET}"
        echo "  NOTICE: Root disk is ${DISK_USAGE_PERCENT}% full." >> "$REPORT_FILE"
    else
        echo -e "  ${GREEN}✅  Disk health is good. Usage: ${DISK_USAGE_PERCENT}%${RESET}"
        echo "  Disk health is good. Usage: ${DISK_USAGE_PERCENT}%" >> "$REPORT_FILE"
    fi

print_section "LAST 5 LOGINS"
last -n 5 2>/dev/null | tee -a "$REPORT_FILE" || echo "  (last command not available)" | tee -a "$REPORT_FILE"

echo "" | tee -a "$REPORT_FILE"
echo "$DIVIDER" | tee -a "$REPORT_FILE"
echo "  END OF REPORT" | tee -a "$REPORT_FILE"
echo "$DIVIDER" | tee -a "$REPORT_FILE"

echo ""
echo -e "${GREEN}✅  Report saved to: ${YELLOW}${REPORT_FILE}${RESET}"
echo -e "${CYAN}    Tip: Open it with:  cat ${REPORT_FILE}${RESET}"
echo ""
