#!/usr/bin/env bash
# =============================================================================
# Script: 01_beginner_system_report.sh
# Problem Statement: Generate a foundational system report covering OS, kernel, CPU, memory, and disk health metrics, outputting to both terminal and file.
# =============================================================================

set -euo pipefail

REPORT_FILE="system_report_$(date '+%Y-%m-%d').txt"
LOG_FILE="${REPORT_LOG_FILE:-}"
USER_NAME=""
DIVIDER="=============================================="

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
CYAN="\033[0;36m"
RED="\033[0;31m"
BOLD="\033[1m"
RESET="\033[0m"

log_info() {
    local msg="$1"
    local ts
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${GREEN}[INFO]${RESET} [${ts}] ${msg}"
    [[ -n "$LOG_FILE" ]] && echo "[INFO] [${ts}] ${msg}" >> "$LOG_FILE"
}

log_warn() {
    local msg="$1"
    local ts
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${YELLOW}[WARN]${RESET} [${ts}] ${msg}"
    [[ -n "$LOG_FILE" ]] && echo "[WARN] [${ts}] ${msg}" >> "$LOG_FILE"
}

log_error() {
    local msg="$1"
    local ts
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${RED}[ERROR]${RESET} [${ts}] ${msg}" >&2
    [[ -n "$LOG_FILE" ]] && echo "[ERROR] [${ts}] ${msg}" >> "$LOG_FILE"
}

print_header() {
    echo -e "${GREEN}${BOLD}"
    echo "  ╔══════════════════════════════════════════╗"
    echo "  ║     🖥   Beginner System Report Script    ║"
    echo "  ╚══════════════════════════════════════════╝"
    echo -e "${RESET}"
}

print_section() {
    local TITLE="$1"
    echo -e "\n${CYAN}>>> ${TITLE}${RESET}"
    printf "\n>>> %s\n" "$TITLE"  >> "$REPORT_FILE"
    echo "$DIVIDER" >> "$REPORT_FILE"
}

generate_report() {
    log_info "Generating system report for user: ${USER_NAME}"

    echo "$DIVIDER"                                > "$REPORT_FILE"
    echo "  SYSTEM REPORT — Generated by: $USER_NAME"  >> "$REPORT_FILE"
    echo "  Date : $(date '+%A, %d %B %Y')"        >> "$REPORT_FILE"
    echo "  Time : $(date '+%H:%M:%S')"            >> "$REPORT_FILE"
    echo "$DIVIDER"                                >> "$REPORT_FILE"

    print_section "BASIC SYSTEM INFORMATION"

    local HOSTNAME CURRENT_USER OS_NAME KERNEL ARCH SHELL_USED
    HOSTNAME=$(hostname)
    CURRENT_USER=$(whoami)
    OS_NAME=$(uname -s)
    KERNEL=$(uname -r)
    ARCH=$(uname -m)
    SHELL_USED=${SHELL:-/bin/bash}

    printf "  %-18s : %s\n" "Hostname"       "$HOSTNAME"         | tee -a "$REPORT_FILE"
    printf "  %-18s : %s\n" "Logged-in User" "$CURRENT_USER"     | tee -a "$REPORT_FILE"
    printf "  %-18s : %s\n" "OS"             "$OS_NAME"          | tee -a "$REPORT_FILE"
    printf "  %-18s : %s\n" "Kernel"         "$KERNEL"           | tee -a "$REPORT_FILE"
    printf "  %-18s : %s\n" "Architecture"   "$ARCH"             | tee -a "$REPORT_FILE"
    printf "  %-18s : %s\n" "Shell"          "$SHELL_USED"       | tee -a "$REPORT_FILE"

    print_section "UPTIME"
    local UPTIME_INFO
    UPTIME_INFO=$(uptime -p 2>/dev/null || uptime)
    echo "  $UPTIME_INFO" | tee -a "$REPORT_FILE"

    print_section "MEMORY USAGE"
    if command -v free &>/dev/null; then
        free -h | tee -a "$REPORT_FILE"
    else
        echo "  'free' command not available on this system." | tee -a "$REPORT_FILE"
    fi

    print_section "DISK USAGE"
    df -h | tee -a "$REPORT_FILE"

    local DISK_USAGE_PERCENT
    DISK_USAGE_PERCENT=$(df / 2>/dev/null | awk 'NR==2 {print $5}' | tr -d '%' || echo "0")
    echo "" | tee -a "$REPORT_FILE"

    if [[ "$DISK_USAGE_PERCENT" =~ ^[0-9]+$ ]] && (( DISK_USAGE_PERCENT >= 80 )); then
        log_warn "Root disk is ${DISK_USAGE_PERCENT}% full! Consider cleanup."
        echo "  WARNING: Root disk is ${DISK_USAGE_PERCENT}% full! Consider cleanup." >> "$REPORT_FILE"
    elif [[ "$DISK_USAGE_PERCENT" =~ ^[0-9]+$ ]] && (( DISK_USAGE_PERCENT >= 60 )); then
        log_info "Notice: Root disk is ${DISK_USAGE_PERCENT}% full."
        echo "  NOTICE: Root disk is ${DISK_USAGE_PERCENT}% full." >> "$REPORT_FILE"
    else
        log_info "Disk health is good. Usage: ${DISK_USAGE_PERCENT}%"
        echo "  Disk health is good. Usage: ${DISK_USAGE_PERCENT}%" >> "$REPORT_FILE"
    fi

    print_section "LAST 5 LOGINS"
    last -n 5 2>/dev/null | tee -a "$REPORT_FILE" || echo "  (last command not available)" | tee -a "$REPORT_FILE"

    echo "" | tee -a "$REPORT_FILE"
    echo "$DIVIDER" | tee -a "$REPORT_FILE"
    echo "  END OF REPORT" | tee -a "$REPORT_FILE"
    echo "$DIVIDER" | tee -a "$REPORT_FILE"

    log_info "Report successfully generated: ${REPORT_FILE}"
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -o|--output|--report-file)
                REPORT_FILE="$2"
                shift 2
                ;;
            -l|--log-file)
                LOG_FILE="$2"
                shift 2
                ;;
            -u|--user)
                USER_NAME="$2"
                shift 2
                ;;
            -h|--help)
                echo "Usage: $0 [OPTIONS]"
                echo "Options:"
                echo "  -o, --output FILE, --report-file FILE   Path to write system report (default: system_report_YYYY-MM-DD.txt)"
                echo "  -l, --log-file FILE                     Path to write structured execution log"
                echo "  -u, --user NAME                         Target username label for report header"
                echo "  -h, --help                              Show this help message and exit"
                exit 0
                ;;
            *)
                log_error "Unknown argument: $1"
                exit 1
                ;;
        esac
    done
}

main() {
    parse_args "$@"

    if [[ -n "$LOG_FILE" ]]; then
        mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true
        : > "$LOG_FILE"
    fi

    if [[ -z "$USER_NAME" ]]; then
        if [[ -t 0 ]]; then
            echo -e "${YELLOW}What is your name?${RESET}"
            read -r USER_NAME || true
        fi
        if [[ -z "$USER_NAME" ]]; then
            USER_NAME="${USER:-${USERNAME:-Developer}}"
        fi
    fi

    print_header
    generate_report
}

main "$@"
